name: camoufox-env
channels:
  - conda-forge
  - nodefaults
  - main
dependencies:
  - python=3.12
  - xorg-xvfb-server
  - gtk3
  - alsa-lib
  - dbus
  - glib
  - xorg-libxcomposite
  - xorg-libxcursor
  - xorg-libxdamage
  - xorg-libxi
  - xorg-libxrandr
  - xorg-libxtst
  - xorg-libxext
  - mesa
  - nss
  - pip
  - pip:
    - -r requirements.txt
